name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Tests and Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@4
      - name: Setup JDK 17
        uses: actions/setup-java@3
        with:
          java-version: '17'
      - name: Cache the build package
        uses: actions/cache@1
        with:
          path: ~/.m2
          key: ${{ os.runner }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ os.runner }}-m2
      - name: Test and build project
        run: mvn -B package --file pom.xml